### PR TITLE
do not use * for mocha

### PR DESCRIPTION
**Pull request by samccone**
eventually there will be version 3, and then your tests may break.

### CODE REVIEW

**Comment by arthurvr** [comment]
Can you go discuss this at https://github.com/sindresorhus/node-module-boilerplate? :)

**Comment by samccone** [comment]
sure, but I still think this is valid for you right?

**Comment by arthurvr** [comment]
I think there's a pretty valid reason for this, otherwise we wouldn't be doing it like that already for years. That's why I suggested to ask it on the boilerplate first.

**Comment by samccone** [comment]
expressed here:
https://github.com/sindresorhus/node-module-boilerplate/issues/8

**Comment by arthurvr** [comment]
(https://github.com/sindresorhus/node-module-boilerplate/issues/8) 

> I prefer to have it loose myself as I can easily fix any potential issues, and don't want to have to bump the version of every little module just because mocha made a tiny breaking change. YMMV.

**Pull request closed without merging**
