### PR TITLE
make random-bit faster on ff

### PR DESCRIPTION
**Pull request by stoeffel**
How do you like this implementation? 
It runs way faster on firefox and a little bit faster on other browsers (see http://jsperf.com/random-bit).
This PR also removes the dependancy to `random-boolean`, since it's not used anymore.

### CODE REVIEW

**Comment by arthurvr** [comment]
I generally prefer code explicitness over micro improvements, but this is a waayyy bigger improvement than I thought, so merging. Thanks.

**Comment by arthurvr** [comment]
Released in 1.0.1. Thanks again :)

**Comment by hemanth** [comment]
:+1:

**Comment by stoeffel** [comment]
np and thanks. Was really surprised too :smiley:

**Pull request merged**
